### ISSUE TITLE
Add DevKit purchase link on the happy path device list page at DOCS

### ISSUE THREAD

**Issue by chyuanmsft** [Microsoft/azure-iot-developer-kit#133]
[For Tracking Purpose]The happy path device list page at DOCS has higher unique visitors than DevKit happy path tutorial. Please refer S124 BI writeup for more details.

**Comment by ArthurMa1978** [comment]
Need to check whether we can do this

**Comment by ArthurMa1978** [comment]
There is not such case in DOCS, the DOCS is developer reference site so put a purchase link here is not make sense, so cut this request
