### ISSUE TITLE
Put devkit tutorials to VS Code docs

### ISSUE THREAD

**Issue by mybayern1974** [Microsoft/azure-iot-developer-kit#134]
VS Code docs (https://code.visualstudio.com/docs) has much higher visiting volume than the current Devkit home page. Given DevKit involves VS Code Arduino Extension, we want to leverage the VS Code Docs power of attracting visiting traffic to open the funnel for DevKit.

**Comment by ArthurMa1978** [comment]
We did talk with VSCode team, will keep following it up

**Comment by ArthurMa1978** [comment]
all docs will move to docs.microsoft.com, code.visualstudio.com is not on the plan.
