### ISSUE TITLE
Feature Request: Add OTA Upload

### ISSUE THREAD

**Issue by rei-vilo** [Microsoft/azure-iot-developer-kit#181]
Add OTA upload to the Azure IoT DevKit.

**Comment by ArthurMa1978** [comment]
This is one of the Azure DPS (Device Provision Service) functions, so we will not support it until DPS release this function

**Comment by rei-vilo** [comment]
@ArthurMa1978 I am not sure to understand your answer. 

By OTA upload, I mean uploading the executable sketch to the board, for example from Visual Studio Code to the board through WiFi on a LAN. It has nothing to do with data and Azure services.

**Comment by ArthurMa1978** [comment]
OTA is on the way https://github.com/Microsoft/devkit-sdk/issues/830
