### ISSUE TITLE
Image in Remote Monitoring guide is possibly out of date?

### ISSUE THREAD

**Issue by jeremylindsayni** [Microsoft/azure-iot-developer-kit#184]
Hi - an image in the [Remote Monitoring guide](https://microsoft.github.io/azure-iot-developer-kit/docs/projects/remote-monitoring/) is displaying something which doesn't seem to be up to date.

The image is at [this location in this repo](https://github.com/Microsoft/azure-iot-developer-kit/blob/master/docs/assets/images/mini-solution/remote-monitoring/build.png). Presently it's showing a couple of files, client sample mqtt.h and client sample mqtt.cpp - these aren't in my Remote Monitoring project.

The fix is to take a new screenshot (or edit the existing one) where only the correct files are shown. 
I hope this helps
Jeremy

**Comment by lirenhe** [comment]
Thanks Jeremy for your feedback. We will update our guide for remote monitoring sample.

**Comment by ArthurMa1978** [comment]
Fixed, thank you Jeremy.
