### ISSUE TITLE
macOS: `install.sh` script doesn't check the active folder

### ISSUE THREAD

**Issue by rei-vilo** [Microsoft/azure-iot-developer-kit#187]
The `install.sh` script provided at [Get Started > Step 5. Prepare the development environment > macOS](https://microsoft.github.io/azure-iot-developer-kit/docs/get-started/#macos)  doesn't check the folder where it is called from.

If launched in the wrong folder, `cp -r * ~/azure-board-cli` could copy the entire folder.

```
#!/bin/bash
rm -rf ~/azure-board-cli
mkdir ~/azure-board-cli
cp -r * ~/azure-board-cli
cd ~/azure-board-cli

rm -rf ~/Library/Arduino15/packages/AZ3166

mkdir -p ~/Library/Arduino15/staging/packages
rsync -u tools/staging/* ~/Library/Arduino15/staging/packages

brew update
brew reinstall yarn
yarn install --production --no-progress

node out/cli.js installation
```

**Comment by rei-vilo** [comment]
This may apply to Windows as well.

**Comment by ArthurMa1978** [comment]
Fixed
