### ISSUE TITLE
CRC Error with Release 1.2.1

### ISSUE THREAD

**Issue by rei-vilo** [Microsoft/azure-iot-developer-kit#195]
Last release 1.2.1 for Arduino seems to have a CRC issue.
 
<img width="800" alt="capture 2017-11-22 a 13 06 18" src="https://user-images.githubusercontent.com/951776/33126765-051ed72a-cf86-11e7-99fc-73e32e73d114.png">

<img width="800" alt="capture 2017-11-22 a 12 55 37" src="https://user-images.githubusercontent.com/951776/33126504-0b6b7080-cf85-11e7-9fb1-04d6203784a2.png">

**Comment by ArthurMa1978** [comment]
thank you for pointing this our, this dl url has been fixed, please clean the folder C:\Users\[your name]\AppData\Local\Arduino15\staging\packages, re-open the boards manager to upgrade the new package
