### ISSUE TITLE
Add a faq of CPP IntelliSense and  include issue in VS Code

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/azure-iot-developer-kit#196]
https://stackoverflow.com/questions/47401731/issues-setting-up-mxchip-vscode-arduino-mx3166-environment-on-mac

**Comment by adumont** [comment]
Although it might seems to work better with Tag Parser, I believe it's not the solution, and actually it should default to Tag Parser, which it doesn't seem to even do:

Comments in Default Settings, C/C++ section say:

>   // Controls the IntelliSense provider. "Tag Parser" provides "fuzzy"
> results that are not context-aware. "Default" provides context-aware
> results and is in preview mode - member list, hover tooltips, and
> error squiggles are currently implemented. Features not yet
> implemented in the new default engine will use the tag parser engine
> instead.   "C_Cpp.intelliSenseEngine": "Default",
> 
>   // Controls whether the IntelliSense engine will automatically
> switch to the Tag Parser for translation units containing #include
> errors.   "C_Cpp.intelliSenseEngineFallback": "Enabled",
