### ISSUE TITLE
[AZ 3166]Fail to reconnect WiFi after call disconnect

### ISSUE THREAD

**Issue by Xeinaemm** [Microsoft/azure-iot-developer-kit#213]
Hey,
I've found issue when I want to implement switch to on/off WiFi. AZ3166 version = 1.2.1 
When I invoke this method
```
static void InitWiFi()
{
  Screen.print(1, "Connecting...");
  while (wifiStatus != WL_CONNECTED)
  {
    wifiStatus = WiFi.begin();
  }
  hasWifi = true;
  Screen.print(3, "> WiFi on");
  EnterIdleState();
}
```
And then
```
static void TurnOffWifi()
{
  Screen.print(1, "Disconnecting...");
  if(hasWifi)
  {
    WiFi.disconnect();
    hasWifi = false;
    wifiStatus = WL_DISCONNECTED;
    Screen.print(3, "> WiFi off");
  }
  delay(1000);
  EnterIdleState();
}
```
Is everything fine, but when I want to reconnect to WiFi by invoking **InitWiFi()** again, device enter into infinite loop. I digged into WiFiClass(AZ3166WiFi.cpp) and found solution. When **begin(void)** method is invoked check for 
```
if (!is_station_inited) 
{
    return WL_CONNECT_FAILED;
}
```
But in **disconnect()** method value of **is_station_inited** is setup to false, so I've changed code above to
```
if (!is_station_inited) 
{
    is_station_inited = InitSystemWiFi();
}
```
In my WiFiClass I've changed also overload of **begin(char\* ssid, const char \*passphrase)** like above.

**Comment by ArthurMa1978** [comment]
Thank you for reporting this issue, will be fixed in next release.
