### ISSUE TITLE
Documentation for manual installation assumes different folder structure of zip file

### ISSUE THREAD

**Issue by ChristianBeier** [Microsoft/azure-iot-developer-kit#242]
When I follow the manual installation instruction
https://microsoft.github.io/azure-iot-developer-kit/docs/installation/
the zip file downloaded in Step 4 does not contain the folder namend "azure-board-cli" but "devkit_task_win_1.2.2.35".

Either the folder name or the documentation should be changed, e.g. extract to "azure-board-cli"

**Comment by ihere1** [comment]
https://github.com/Microsoft/azure-iot-developer-kit/commit/1121e98c927b3a21ef2df84242a6403e36bd377f 
Fix command in document.

**Comment by ArthurMa1978** [comment]
please pr to pre-release with the same change
