### ISSUE TITLE
AZ3166 package version and installation script version don't match

### ISSUE THREAD

**Issue by vsctest1** [Microsoft/azure-iot-developer-kit#258]
steps:
1. download Installation packages: devkit_install_win_1.2.2.35
2. run installation script as administrator.
3. go to folder \AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.3.0
Actually : the version  of AZ3166 package is 1.3.0,  but Expected version is 1.2.2.

**Comment by ArthurMa1978** [comment]
fixed in 1.3.1
