### ISSUE TITLE
the AZ3166 package was not generated under normal user folder after run installation package script

### ISSUE THREAD

**Issue by vsctest1** [Microsoft/azure-iot-developer-kit#259]
Steps:
1.login in computer, here user's login account is not administrator.
2. run installation package script as administrator : devkit_install_win_1.3.0.40
3.verify the AZ3166 package not install under folder C:\Users\login user\AppData\Local\Arduino15 ,
 but  install AZ3166 package under C:\Users\admin user\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.3.0

**Comment by Sneezry** [comment]
If the current user is not administrator, but you run the script as administrator, you must use another user to provide permission, and the script is called by the administrator user in fact. So this is not bug. The installation script shouldn't be called as administrator.
