### ISSUE TITLE
Add hints for homebrew prerequisites

### ISSUE THREAD

**Issue by chyuanmsft** [Microsoft/azure-iot-developer-kit#262]
For tracking purpose. Some people may do not have Apple Command Line Tools installed so installation for Mac package would fail.

**Comment by Sneezry** [comment]
https://mseng.visualstudio.com/VSIoT/IoT%20Dev%20Kit/_git/IoTDevKitInstallation.Win/pullrequest/300945

**Comment by ArthurMa1978** [comment]
Assign to Chen for testing confirmation

**Comment by czgtest** [comment]
The code fix verify pass on Mac.
if not have Apple Command Line Tools installed,  the installation script will check and reminder user to install,
![image](https://user-images.githubusercontent.com/35018765/35423799-aea4a928-028a-11e8-82de-72b82512424c.png)
if already have Apple Command Line Tools installed,  the installation script will skip and continue next step.

**Comment by ArthurMa1978** [comment]
will be released in 1.3.2
