### ISSUE TITLE
Add a how-to doc to describe how to customize the deviceId

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/azure-iot-developer-kit#269]

**Comment by Sneezry** [comment]
Should we public this feature in the docs? Customized deviceId is for Air Traffic Control Simulator in the workshop only, and if users use it in other mini solutions, such as Shake Shake, they may meet errors.

**Comment by jantielens** [comment]
Can't we read the deviceid from the IoT Hub connection string?

`    String connstr = readConnectionString();
    int i = connstr.indexOf("DeviceId=");
    int j = connstr.indexOf(";", i);
    String deviceid = connstr.substring(i + 9, j);
    json_object_set_string(root_object, "deviceId", deviceid.c_str());`

And this is my implementation of readConnectionString

`String readConnectionString()
{
    EEPROMInterface eeprom;
    uint8_t connectionString[255];
    eeprom.read((uint8_t *)connectionString, 255, 0, 5);
    return String((const char *)connectionString);
}`

**Comment by ArthurMa1978** [comment]
@jantielens thank you for your suggestion.
Here the issue is customized the deviceId for iothub provision and create the device in iothub, not read the deviceid on device.

**Comment by Sneezry** [comment]
https://github.com/Microsoft/azure-iot-developer-kit/pull/281
