### ISSUE TITLE
Minor problems with scroll-to-top UI item [site]

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/azure-iot-developer-kit#272]
- [x] it blends into content - if available on the page

Here on the FAQ page:

![20180124214235](https://user-images.githubusercontent.com/14539/35356743-9940a6b6-0151-11e8-810d-c1024e0cada4.jpg)

- [ ] it appears only on one path, not on the other

I think: either use it accross all long pages (docs, how-to-guides) or do not use at all

- [x] the footer obstructs it and prevents its use

![image](https://user-images.githubusercontent.com/14539/35356845-eb092176-0151-11e8-83c0-77198bcc750f.png)

I could make a PR, but let me know if what's expected fix (if any, I expected #1 and #3 to be easily fixable)

Thanks!

**Comment by ArthurMa1978** [comment]
@peterblazejewicz  thank your, please just send the pr out :)

**Comment by peterblazejewicz** [comment]
@ArthurMa1978 this could be closed. The No1 and No3 are fixed, the No2 is something for consideration
thanks!
