### ISSUE TITLE
Minor issue with page footer z-index [site]

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/azure-iot-developer-kit#277]
Small issue, again with page footer. The footer should not obstruct or cover other important user traits:

Here the report issue:
![image](https://user-images.githubusercontent.com/14539/35410432-b7b6621a-0215-11e8-8fd3-11c26750766b.png)

Thanks!

**Comment by Sneezry** [comment]
https://github.com/Microsoft/azure-iot-developer-kit/pull/279
