### ISSUE TITLE
Consider supporting of the  browser back button features when bookmarking is added [site]

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/azure-iot-developer-kit#291]
Hi,

It seems that the site relies on the `jquery-smooth-scroll` for scrolling a content from the TOC.
https://github.com/Microsoft/azure-iot-developer-kit/search?utf8=%E2%9C%93&q=smoothScroll&type=

I think it could be beneficial for the user experience when using docs to enhance the TOC navigation with browser based features.

The plugin supports both bookmarking and browser navigation with smooth scroll eanbled and here is their own sample I've put online that shows that feature:
https://s.codepen.io/blazejewicz/debug/ee1b1462aa2dbe20971ff031aa9c124d#/p4
https://s.codepen.io/blazejewicz/debug/ee1b1462aa2dbe20971ff031aa9c124d#/p2

Thanks!

**Comment by ArthurMa1978** [comment]
thank you for your suggestion, will put into our backlog

**Comment by ArthurMa1978** [comment]
We will refactor the site for the IoT Workbench, so the ToC would be re-designed.
