### ISSUE TITLE
Optimize assets size with svgo/imageoptim Jekyll plugins or NPM modules

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/azure-iot-developer-kit#323]
Hi,

This page for example hosts 7 JPEG images ranging +1mb in size:
https://microsoft.github.io/azure-iot-developer-kit/docs/projects/devkit-translator/

![image](https://user-images.githubusercontent.com/14539/36231766-9385c73a-11df-11e8-8bf4-4d450c24bb18.png)
These are scaled down full-size images. The scaling is done by client, the full version of the image is sent through the wire

https://github.com/valerijaspasojevic/jekyll-compress-images

The VSCode editor cannot even render preview of that files having limit to 1mb of filesize
I can run some Adobe Photoshop optimization on some assets (just to lower compression ration on JPEG without changing output quality.

The additional problem for this is that these assets seem to have a very short cache 10 m TTL (issue on github.io pages). So the content of this type will be re-fetched

Thanks!

**Comment by ArthurMa1978** [comment]
have been moved to docs.microsoft.com, and reduced the picture
