### ISSUE TITLE
ArduinoJson is required to build MXChip AZ3166 firmware

### ISSUE THREAD

**Issue by ylashin** [Microsoft/azure-iot-developer-kit#352]
After following the installation steps listed below, building MXChip firmware fails complaining that ArduinoJson.h is missing. 

https://microsoft.github.io/azure-iot-developer-kit/docs/installation/

`sketch\src\iotHubClient.cpp:7:25: fatal error: ArduinoJson.h: No such file or directory`

This library does not come by default with Arduino IDE.
We can use VS Code Arduino Library Manager or  install it manually from: https://arduinojson.org/doc/installation/

![image](https://user-images.githubusercontent.com/2197158/37693602-7a1e617e-2d0c-11e8-8116-21dea5123bc4.png)

Assuming the above is valid, it could be a good idea to include this library in the installation steps.

**Comment by ylashin** [comment]
Hi @ArthurMa1978 

I encountered this issue when building the firmware code for AZ3166 that comes as part of Microsoft IoT central framework. This was part of a Microsoft IoT workshop I had last week.

https://github.com/Microsoft/microsoft-iot-central-firmware/tree/master/AZ3166

**Comment by ArthurMa1978** [comment]
@ylashin ok, I will check with IoT Central team if they can remove this dependence.
As Arduino don't have package management like nod.js has, so any dependences have to install manually.

**Comment by ArthurMa1978** [comment]
@ylashin the code has been fixed, please pull the latest code from https://github.com/Azure/iot-central-firmware
