### ISSUE TITLE
Add a doc to explain 'how to' disable data collection at the begin

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/azure-iot-developer-kit#353]
https://mseng.visualstudio.com/VSIoT/IoT%20Dev%20Kit/_git/IoTDevKitInstallation.Win/pullrequest/307988

**Comment by ihere1** [comment]
https://github.com/Microsoft/azure-iot-developer-kit/pull/357/files

**Comment by ihere1** [comment]
https://github.com/Microsoft/azure-iot-developer-kit/pull/357

**Comment by ArthurMa1978** [comment]
https://github.com/Microsoft/azure-iot-developer-kit/pull/366
