### ISSUE TITLE
30-days free trail Azure account link is broken

### ISSUE THREAD

**Issue by liydu** [Microsoft/azure-iot-developer-kit#354]
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-translator

The link of "free 30-day trial Microsoft Azure account" is broken.

It should be https://azure.microsoft.com/en-us/free/

**Comment by v-mavick** [comment]
v-mavick submitted PR "Corrected broken link to Free Azure subscription page. #36343" to correct this link in the following three documents:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-devkit-remote-monitoring
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-translator
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-retrieve-twitter-message

**Comment by liydu** [comment]
Reopen it until the PR have been merged to msdocs.

**Comment by liydu** [comment]
All resolved
