### ISSUE TITLE
Latest Firmware Link not pointing to latest firmware

### ISSUE THREAD

**Issue by c0g1t8** [Microsoft/azure-iot-developer-kit#361]
My device was showing a newer firmware _1.3.4_ was available. It was currently at _1.3.3_.  

Used the download link provided on https://microsoft.github.io/azure-iot-developer-kit/docs/firmware-upgrading/
![image](https://user-images.githubusercontent.com/23250332/38170486-899786b2-353b-11e8-9e46-ff00830b9ef2.png)
Download was to the _1.3.3_ firmware not to _1.3.4_

The link underlying is https://aka.ms/devkit/prod/firmware/latest.  It's not pointing to the latest version.

**Comment by ArthurMa1978** [comment]
Thanks @c0g1t8 for reporting this issue, fixed.
