### ISSUE TITLE
Newly released version should be 1.4.0 not 1.3.5

### ISSUE THREAD

**Issue by obastemur** [Microsoft/azure-iot-developer-kit#373]
`1.3.5` goes beyond fixing bugs and adds new API hence it shouldn't be 1.3.5 but it should be `1.4.0`

**Comment by ArthurMa1978** [comment]
The 1.4.0 is reserved for our new ota feature, which may bring some breaking changes.
We have 1.3.7 which should be released last week, but unfortunatly got some underlying RTX issue, so had to move it to this week.
