### ISSUE TITLE
attachInterrupt(USER_BUTTON_B,...) & new LSM6DSLSensor(*i2c, D4, D5)

### ISSUE THREAD

**Issue by Adamantinu** [Microsoft/azure-iot-developer-kit#386]
If you attach an Interrupt to the User_Button_B and add the LSM6DSLSensor for the gyroscope, the interrupt is not working anymore.

EDIT: Same Code works as expected when attaching the interrupt to USER_BUTTON_A instead

**Comment by ArthurMa1978** [comment]
This issue was moved to Microsoft/devkit-sdk#895
