### ISSUE TITLE
SOURCE CODE

### ISSUE THREAD

**Issue by orubel** [Microsoft/azure-iot-developer-kit#390]
Your pages on the site and product pages do not distribute ( or have links) to open source source code.

You product distributes open source code and trademarks which do not have the code distributed with the products. Key components have been rewritten but you are using a large number of libraries and documents that still fall under the licensing.

If Microsoft is a good steward, I suspect it will not need to delete this and can easily comply with all the licensing requirements.

Please do not ask hwerein you have missed the licensing requirements. You are embedding Linux on chip and 'distributing'. Even with the rewrites, one can clearly see massive amounts of noncompliance.

**Comment by ArthurMa1978** [comment]
Why do you think it's Linux? the underlying RTOS is mbedOS5, and we have all source code opened in GitHub:
https://github.com/VSChina/mbed-os
https://github.com/VSChina/mbed-emw10xx-driver
https://github.com/Microsoft/devkit-sdk
