### ISSUE TITLE
Extraneous javascript present in instructions in MxChip tutorial 

### ISSUE THREAD

**Issue by rukmani-msft** [Microsoft/azure-iot-developer-kit#424]
Remove the javascript instructions from MxChip instructions - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started

![image](https://user-images.githubusercontent.com/43420178/45993893-e6aa5880-c045-11e8-98a5-e3ff7077ef83.png)

**Comment by likidu** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/53338

**Comment by liydu** [comment]
@rukmani-msft , got this one fixed.
