### ISSUE TITLE
Need to indicate more clearly order of tools install

### ISSUE THREAD

**Issue by olivierbloch** [Microsoft/azure-iot-developer-kit#426]
In the getting started documentation/setup your environment section, there is a note recommending the use of the workbench extension to work with the devkit (with a link to the extension). Users have a tendency of clicking this link and installing the extension before reading what's below and installing the Arduino IDE. If the workbench extension is installed before the Arduino IDE then the extension won't work properly. 

I recommend we remove the link in the first sentence to "force" reader to go through the steps in order and to add a note that the order of the steps below is important.

**Comment by ArthurMa1978** [comment]
#427

**Comment by olivierbloch** [comment]
I think the update solves the issue, thanks
