### ISSUE TITLE
Links to task scripts for IoT DevKit are invalid

### ISSUE THREAD

**Issue by toolboc** [microsoft/azure-iot-developer-kit#451]
On the manual installation page @ https://microsoft.github.io/azure-iot-developer-kit/docs/installation/ there are links to obtain task scripts for IoT DevKit.  

These links are currently invalid:
* https://aka.ms/devkit/prod/installpackage/tasks/latest
* https://aka.ms/devkit/prod/installpackage/mac/latest

These tasks are required for certain MXChip labs, specifically the Air Traffic Control Simulator: https://microsoft.github.io/azure-iot-developer-kit/docs/projects/air-traffic-control-simulator/

FWIW, 

I was able to workaround with an older link to the tasks @ https://azureboard2.azureedge.net/prod/windows/devkit_install_win_1.3.0.40.zip
https://azureboard2.azureedge.net/prod/mac/devkit_install_mac_1.3.0.40.zip

This required that I stub telemetry.trace in telemetry.js as it pointed to a 404'd server and fix task-device.js to use the proper az cli syntax for iot interactions.  Any ideas where these tasks are maintained?

**Comment by JerryYangKai** [comment]
Hi @toolboc, I have fixed the link and updated to the latest version. This page is deprecated and I suggest you can use Board Manager in Arduino extension to install it now.
