### ISSUE TITLE
Changing the IoT Hub & device never updates

### ISSUE THREAD

**Issue by pkimbell** [microsoft/azure-iot-developer-kit#459]
I have the MX Chip Remote Monitoring example running and configured to use Hub1 and Device1 (example), we have updated to a paid subscription and we need to change the IoT Hub information to Hub2 and Device2.  I used the "Azure IoT Device Workbench: Provision Azure Services" action which did prompt and did allow me to select the correct options.  The "Azure IoT Device Workbench" output showed the correct information, however, data is still flowing to the old config after the device restarts.  We disabled the old config in Azure and the MX Chip stopped connecting to Azure.  I then tried to update the IoT config again and it still sends the data to the old IoT Hub (after updating the MX Chip).  Uploading to the MX Chip device multiple times, restarting multiple times, nothing will change the connection when the device boots up.  What am I missing?

**Comment by JerryYangKai** [comment]
Hi, the new config did not write to your mxchip so it followed the old config.  You can try this commend "Configure Device Settings" after provision.
