### ISSUE TITLE
HttpClient.h all HTTPS GET calls fail

### ISSUE THREAD

**Issue by DerekFoster1976** [microsoft/azure-iot-developer-kit#462]
Cannot get any HTTPS REST calls to work. Have tried multiple APIs with correct cert fingerprint. Even the official sample code for HttpClient using HTTPS [here](https://microsoft.github.io/azure-iot-developer-kit/docs/apis/http-client/) doesn't work either. HTTP REST calls work fine. There is a lot of discussion around this for standard Arduino sketches. A solution would be great as essentially can't call most APIs directly from the board as they all use HTTPS.

**Comment by JerryYangKai** [comment]
Hi @DerekFoster1976 , We have released DevKit SDK 1.6.5 and HttpClient supporting HTTPS now. Please try it.
