### ISSUE TITLE
Links to the aquire MXChip device return HTTP 404 Error

### ISSUE THREAD

**Issue by jaredpsimpson** [Microsoft/azure-iot-developer-kit#470]
The following links throughout the repo return an HTTP 404 error:

- http://www.mxchip.com/az3166
- https://aka.ms/iot-devkit-purchase
- http://mxchip.com/az3166

To reproduce:

1. Goto https://microsoft.github.io/azure-iot-developer-kit/
2. Click on 'Get a Kit'
3. You will notice that the underlying link is "https://aka.ms/iot-devkit-purchase" and redirects to "http://mxchip.com/az3166"
4. This returns a "404: Not Found" before redirecting to the http://mxchip.com website.

**Comment by ArthurMa1978** [comment]
Fixed, sorry for taking so long to fix this issue.
