### ISSUE TITLE
WiFi.macAddress not working

### ISSUE THREAD

**Issue by baywet** [microsoft/azure-iot-developer-kit#475]
I have been trying for a couple of hours now to read the mac adress using the API instead of hardcoding it.
https://microsoft.github.io/azure-iot-developer-kit/docs/apis/wifi/#macaddress
However this API never returns anything, sdk v1.6.2, trying after the wifi has been initialized with this piece of code
```C
unsigned char * macAddress;
    WiFi.macAddress(macAddress);
    Screen.print(3, (char *)macAddress);
```

**Comment by dooriya** [comment]
@baywet Thank you for the feedback!
To get the Wi-Fi mac address for MXChip DevKit, could you try the following code snippet? 

```cpp
void printMacAddress() {
    unsigned char mac[WL_MAC_ADDR_LENGTH];
    WiFi.macAddress(mac);
    char macString[18];
    
    sprintf(macString, "%02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);

    // Print to screem
    Screen.print(0, "MAC address:");
    Screen.print(1, macString, true);

    // Print to serial port
    Serial.printf("Mac address: %s\r\n", macString);
}
```

It should be work:
![image](https://user-images.githubusercontent.com/10163840/65825458-bd03bd00-e2a9-11e9-9a3e-7e3c8368d92a.png)

**Comment by baywet** [comment]
Thanks for the answer. I have moved on to other projects since. Closing
