### ISSUE TITLE
Arduino Board Manager not opening without Arduino IDE installed

### ISSUE THREAD

**Issue by chadmichaels** [microsoft/azure-iot-developer-kit#484]
When following the getstarted guide, step #6, VSCode can cycle back to the Settings page instead of displaying the Arduino Board Manager menu. Installing the Arduino IDE established the path C:\\Program Files (x86)\\Arduino which fixed the issue.

Discovered workaround/solution on this blog: http://www.notyourdadsit.com/blog/2019/5/8/troubleshooting-arduino-board-manager-fails-to-run-in-vscode

**Comment by ArthurMa1978** [comment]
this is by design, Arduino IDE is mandatory for Arduino extension
