### ISSUE TITLE
There aren't any docs on using the second Serial port

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/azure-iot-developer-kit#491]
As the title really.

There are no docs on how to enable the second serial port to stream data from a connected device. It would be good to cover how to do this, then refer to the Arduino Serial docs.

```c
// Declare a new Serial using the second serial port
UARTClass Serial1(UART_1);
```

I'm happy to write these docs if it is agreed they are needed.

**Comment by liydu** [comment]
@jimbobbennett , that will be fantastic. Please let me know if you have PR for this and we can merge it back to the official doc.

**Comment by jimbobbennett** [comment]
@liydu - PR raised with some docs. Let me know your thoughts.
