### ISSUE TITLE
The contributing guide refers to the SDK, not docs

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/azure-iot-developer-kit#493]
As the title really, [CONTRIBUTING.md](https://github.com/microsoft/azure-iot-developer-kit/blob/pre-release/CONTRIBUTING.md) contains references to building and testing the SDK, whereas this repo is for the docs.

It would be helpful if this could be updated to refer to the docs and provide instruction on building the static site.

**Comment by JerryYangKai** [comment]
Hi @jimbobbennett , you can fork this repo and use GitHub Pages to deploy, then submit a pull request to contributing this docs. 

Of course we will also replace CONTRIBUTING.md to a new one. Thanks.
