### ISSUE TITLE
AppVeyor build fails

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/azure-iot-developer-kit#499]
Looks like your AppVeyor build "continuous-integration/appveyor/pr" is broken. There are a couple PRs (#481 #485) on this project that are for typo fixes that haven't been accepted yet, and the AppVeyor build shows that they've failed.

Is this AppVeyor build still needed on the repo? Also, is there a better way to submit PRs than in this repo?

Thanks! :)

**Comment by liydu** [comment]
Hi @crpietschmann , I have merged the doc updates. In the meanwhile, we will look into the AppYeyor issue.

For the issues around DevKit, you can either submit PR in this repo or in the DevKit SDK repo: https://github.com/microsoft/devkit-sdk

**Comment by likidu** [comment]
Add @JerryYangKai to help it.

**Comment by liydu** [comment]
Add @JerryYangKai to help on it.

**Comment by JerryYangKai** [comment]
Hi, all. I have fixed it in pr #495 . And up to the latest version.
