### ISSUE TITLE
Source code repository

### ISSUE THREAD

**Issue by baqwas** [microsoft/azure-iot-developer-kit#506]
Hello,

"_Newbie_" here, where is the link to the source code repositories for the projects listed in this section? I did browse the several folders but could not find any code although there were examples referencing the inner workings of these under VS Code.

I have VS Code installed under Ubuntu 19.10 but did not find any Extensions that had the basic codes.

Thanks.

**Comment by JerryYangKai** [comment]
Hi @baqwas , all the samples are [here](https://docs.microsoft.com/en-us/samples/browse/?term=mxchip), you can find the source code by click 'Browse code' button in each docs.

**Comment by baqwas** [comment]
@JerryYangKai Thanks a bunch!
