### ISSUE TITLE
The board shots should be redone with softer lights 

### ISSUE THREAD

**Issue by liydu** [Microsoft/azure-iot-developer-kit#79]
Suggested by @jonbgallant 

Current images have glare.  Even consider a lightbox.

**Comment by v-mavick** [comment]
I designed a photo rig and printed it on my 3D printer. It has four component pieces:
- a panel which securely holds a DevKit board.
- an LED light bar to illuminate the DevKit (prototype version shown in photo).
- a panel to hold an old iPhone I happened to have (to take photos of the DevKit board).
- a base unti, which securely holds the other three components in precise alignment.

The whole assembly is collapsible for easy transport.
![devkit photo rig](https://user-images.githubusercontent.com/33636473/34471849-20bd355c-ef08-11e7-9258-fb3441f4ac0c.jpg)
Here is a sample (unedited) photo taken with this setup...
![devkit sample photo](https://user-images.githubusercontent.com/33636473/34471852-3ea88e0e-ef08-11e7-96f6-548fca2be863.jpg)
As you can see, using this rig virtually eliminates the glare while making all of the components, silk-screened legends, and the onboard screen very clear and readable.

**Comment by v-mavick** [comment]
Arthur,

Here’s the first one… More to follow quickly.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-retrieve-twitter-message

Please let me know if these are acceptable.

Thanks,
Marc Vick (Aquent LLC)

**Comment by ArthurMa1978** [comment]
the photo looks pretty good, thank you Marc!
