### ISSUE TITLE
Should mention what the risks are here if everything is stored in clear text

### ISSUE THREAD

**Issue by liydu** [Microsoft/azure-iot-developer-kit#80]
Suggested by @jonbgallant 

> After WiFi is configured, your credentials will be persisted on the device for that connection, even if unplugged. For example, if you configured the DevKit for WiFi in your home and then took the DevKit to the office, you will need to reconfigure AP mode (starting at step 3A) to connect the DevKit to your office WiFi.

**Comment by ArthurMa1978** [comment]
as a devkit I think it's not a problem.
