### ISSUE TITLE
Use Acrolinx to validate the content

### ISSUE THREAD

**Issue by liydu** [Microsoft/azure-iot-developer-kit#82]
[Acrolinx for VS Code](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-acrolinx-vscode?branch=master)

Pages requires validation:
* https://microsoft.github.io/azure-iot-developer-kit/docs/faq/ , too much personality, “player”, “awesome”, etc.

**Comment by ArthurMa1978** [comment]
The Acrolinx only can be used in VS Code.
